services:
  mongodb:
    image: mongo:7.0.31-jammy
    container_name: mongodb
    
    ports:
      - "27007:27017"

    volumes:
      - mongodatabase:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend

    restart: always
  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant

    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API

    volumes:
      - qdrantdatabase:/qdrant/storage

    networks:
      - backend

    restart: always
networks:
  backend:

volumes:
  mongodatabase:
  qdrantdatabase:
