services:
  mongodb:
    image: mongo:7.0.31-jammy
    container_name: mongodb
    
    ports:
      - "27007:27017"

    volumes:
      - mongodatabase:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend

    restart: always

  pgvector:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: pgvector
    ports:
      - "5432:5432"
    
    volumes:
      - pgvector_data:/var/lib/postgresql/data

    environment:  
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
    
    networks:
      - backend

    restart: always

networks:
  backend:

volumes:
  mongodatabase:
  pgvector_data:
