server{
    listen 80;
    server_name localhost;

    location / {
                proxy_pass http://fastapi:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
   
            } 

    location /rag_ishms_metrics_v__0{
        proxy_pass http://fastapi:8000/rag_ishms_metrics_v__0;
    }

}


